baseURL = "https://blog.kushagraj.xyz"
languageCode = "en-us"
title = "TheSillyScibbles" # the title of your site

theme = "kishy"

[params]
  author = "Kushagra J" # the author of the site
  description = "exloring tech, thought and whimsy" # a description of your site that will be used in the meta tags

  [params.homeInfoParams]
    Title = "Hey There! I'm Kushagra 👋" # the text to display on the "/" homepage
    Content = "exloring tech, thought and whimsy"
    Description = "A minimal web log." # The description of the home page that will be used in the open graph meta tags
[markup.goldmark.renderer]
  unsafe = true
