baseurl      = "https://kushagra-xo.github.io/thesillyscribbles/"
title        = "The Silly Scribbles"
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'kushagra-xo'                 # github.com/YOUR_GITHUB_ID
  mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://i.pinimg.com/736x/94/f5/24/94f52427cf3d8ad32c342a8cd3133c75.jpg'                 # gravatar email or image url
  name = 'Kushagra J'
  bio = 'a personal blog'


  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
