baseurl      = "https://kushagra-xo.github.io/thesillyscribbles/"
title        = "The Silly Scribbles"
theme = 'paper'

[params]
  # header social icons
  github = 'kushagra-xo'
  rss = true 

  # home page profile
  avatar = 'https://i.pinimg.com/736x/94/f5/24/94f52427cf3d8ad32c342a8cd3133c75.jpg'                 # gravatar email or image url
  name = 'Kushagra J'
  bio = 'a personal blog'

  # misc
  disableHLJS = false                       # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
[params.giscus]
  repo = 'kushagra-xo/thesillyscribbles'                 # see https://giscus.app for more details
  repoId = 'R_kgDOKgNgag'
  category = 'General'
  categoryId = 'DIC_kwDOKgNgas4Ca8AM'
  mapping = 'pathname'
  theme = 'preferred_color_scheme'
  lang = 'en'
